drop table if exists phones;

create table phones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)  primary key,
  model varchar(254)  not null,
  color VARCHAR (50) NOT  NULL,
  displaySize SMALLINT NOT NULL,
  width SMALLINT,
  length SMALLINT,
  camera SMALLINT,
  price INT not null
);
